import { apiAdmin } from "@/lib/admin";
import { createSupabaseAdminClient } from "@/lib/supabase";
import { deleteR2Object, getR2ObjectText, putR2Object } from "@/lib/r2";
const unauthorized=()=>Response.json({error:"Админ эрх шаардлагатай."},{status:401});
const normalizeVtt=(value:string)=>{const clean=value.replace(/^\uFEFF/,"").replace(/\r\n/g,"\n").trim();return clean.startsWith("WEBVTT")?`${clean}\n`:`WEBVTT\n\n${clean.replace(/(\d{2}:\d{2}:\d{2}),([0-9]{3})/g,"$1.$2")}\n`;};
const mapTrack=(row:{id:string;label:string;language:string;object_key:string;original_filename:string})=>({id:row.id,label:row.label,language:row.language,key:row.id,originalFilename:row.original_filename,objectKey:row.object_key});
export async function GET(request:Request,{params}:{params:Promise<{id:string}>}){if(!(await apiAdmin()))return unauthorized();const {id}=await params;const db=createSupabaseAdminClient();const trackId=new URL(request.url).searchParams.get("trackId");if(trackId){const {data,error}=await db.from("subtitles").select("id,label,language,object_key,original_filename").eq("movie_id",id).eq("id",trackId).maybeSingle();if(error)return Response.json({error:error.message},{status:500});if(!data)return Response.json({error:"Subtitle олдсонгүй."},{status:404});return Response.json({track:{...mapTrack(data),content:await getR2ObjectText(data.object_key)}});}const {data,error}=await db.from("subtitles").select("id,label,language,object_key,original_filename").eq("movie_id",id);if(error)return Response.json({error:error.message},{status:500});return Response.json({tracks:(data??[]).map(mapTrack)});}
export async function POST(request:Request,{params}:{params:Promise<{id:string}>}){if(!(await apiAdmin()))return unauthorized();const {id}=await params;const body=await request.json() as {trackId?:string;label?:string;language?:string;filename?:string;content?:string};if(!body.label?.trim()||!body.language?.trim()||!body.content?.trim())return Response.json({error:"Subtitle-ийн нэр, хэл, агуулгыг бүрэн оруулна уу."},{status:400});if(body.content.length>2_000_000)return Response.json({error:"Subtitle файл хэт том байна."},{status:413});const db=createSupabaseAdminClient();const existing=body.trackId?(await db.from("subtitles").select("id,object_key").eq("id",body.trackId).eq("movie_id",id).maybeSingle()).data:null;const trackId=existing?.id??crypto.randomUUID();const objectKey=existing?.object_key??`subtitles/${id}/${trackId}.vtt`;await putR2Object(objectKey,Buffer.from(normalizeVtt(body.content),"utf8"),"text/vtt; charset=utf-8");const payload={id:trackId,movie_id:id,label:body.label.trim(),language:body.language.trim().toLowerCase(),object_key:objectKey,original_filename:body.filename?.trim()||"subtitle.vtt"};const {data,error}=await db.from("subtitles").upsert(payload).select("id,label,language,object_key,original_filename").single();if(error)return Response.json({error:"Subtitle хадгалж чадсангүй: "+error.message},{status:500});const {data:all}=await db.from("subtitles").select("id,label,language,object_key,original_filename").eq("movie_id",id);return Response.json({track:mapTrack(data),subtitles:(all??[]).map(mapTrack)});}
export async function DELETE(request:Request,{params}:{params:Promise<{id:string}>}){if(!(await apiAdmin()))return unauthorized();const {id}=await params;const trackId=new URL(request.url).searchParams.get("trackId");if(!trackId)return Response.json({error:"Subtitle олдсонгүй."},{status:404});const db=createSupabaseAdminClient();const {data}=await db.from("subtitles").select("object_key").eq("id",trackId).eq("movie_id",id).maybeSingle();if(!data)return Response.json({error:"Subtitle олдсонгүй."},{status:404});await deleteR2Object(data.object_key).catch(()=>{});await db.from("subtitles").delete().eq("id",trackId);const {data:all}=await db.from("subtitles").select("id,label,language,object_key,original_filename").eq("movie_id",id);return Response.json({subtitles:(all??[]).map(mapTrack)});}
