'use client';
import { useRef, useState } from 'react';
import type { ContentItem } from '@/lib/content';
const categories = ['Адал явдал','Драма','Инээдмийн','Триллер','Гэмт хэрэг','Түүхэн','Гэр бүлийн','Баримтат'];
type UploadState='idle'|'uploading'|'processing'|'done'|'error';
export function AdminMovies({initial}:{initial:ContentItem[]}){
 const [items,setItems]=useState(initial);const [open,setOpen]=useState(false);const [title,setTitle]=useState('');const [synopsis,setSynopsis]=useState('');const [selectedCategories,setSelectedCategories]=useState<string[]>([]);const [video,setVideo]=useState<File|null>(null);const [uploadState,setUploadState]=useState<UploadState>('idle');const [progress,setProgress]=useState(0);const [error,setError]=useState('');const fileInput=useRef<HTMLInputElement>(null);
 const reset=()=>{setTitle('');setSynopsis('');setSelectedCategories([]);setVideo(null);setProgress(0);setUploadState('idle');setError('')};
 const close=()=>{if(uploadState==='uploading')return;setOpen(false);reset()};
 const toggleCategory=(category:string)=>setSelectedCategories(current=>current.includes(category)?current.filter(item=>item!==category):[...current,category]);
 async function uploadMovie(event:React.FormEvent){event.preventDefault();if(!title.trim()||!synopsis.trim()||selectedCategories.length===0||!video){setError('Нэр, тайлбар, ангилал болон видео файлаа бүрэн оруулна уу.');return}setError('');setUploadState('uploading');setProgress(0);try{
  const initResponse=await fetch('/api/admin/uploads',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'init',filename:video.name,contentType:video.type||'application/octet-stream'})});if(!initResponse.ok)throw new Error('Upload эхлүүлэх боломжгүй байна.');const {key,uploadId}=await initResponse.json() as {key:string;uploadId:string};const chunkSize=8*1024*1024;const parts:{partNumber:number;etag:string}[]=[];
  for(let offset=0,partNumber=1;offset<video.size;offset+=chunkSize,partNumber+=1){const chunk=video.slice(offset,Math.min(offset+chunkSize,video.size));const response=await fetch(`/api/admin/uploads?key=${encodeURIComponent(key)}&uploadId=${encodeURIComponent(uploadId)}&part=${partNumber}`,{method:'PUT',body:chunk});if(!response.ok)throw new Error(`${partNumber}-р хэсгийг upload хийж чадсангүй.`);parts.push(await response.json() as {partNumber:number;etag:string});setProgress(Math.round(Math.min(offset+chunkSize,video.size)/video.size*100))}
  setUploadState('processing');const completeResponse=await fetch('/api/admin/uploads',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'complete',key,uploadId,parts,movie:{title:title.trim(),synopsis:synopsis.trim(),categories:selectedCategories,filename:video.name,bytes:video.size,contentType:video.type}})});if(!completeResponse.ok)throw new Error('Киноны бүртгэлийг хадгалж чадсангүй.');const {id,slug}=await completeResponse.json() as {id:string;slug:string};setItems(current=>[{id,slug,title:title.trim(),synopsis:synopsis.trim(),year:new Date().getFullYear(),duration:'Боловсруулж байна',age:'13+',rating:0,genre:selectedCategories,kind:'movie',status:'processing',accent:'#581018',videoKey:key},...current]);setUploadState('done');setTimeout(()=>{setOpen(false);reset()},1200)
 }catch(uploadError){setUploadState('error');setError(uploadError instanceof Error?uploadError.message:'Upload хийхэд алдаа гарлаа.')}}
 return <><div className="admin-toolbar"><div><h1>Кино</h1><p>{items.length} бүтээл · каталогийн удирдлага</p></div><button className="primary-button" onClick={()=>setOpen(true)}>＋ Кино upload хийх</button></div><div className="admin-table"><div className="table-head"><span>БҮТЭЭЛ</span><span>ТӨРӨЛ</span><span>ТӨЛӨВ</span><span>ОН</span><span/></div>{items.map(item=><div className="table-row" key={item.id}><div className="title-cell"><i style={{background:item.accent}}/><span><b>{item.title}</b><small>{item.videoKey?'Видео хадгалагдсан':item.slug}</small></span></div><span>{item.kind==='movie'?'Кино':'Цуврал'}</span><span className={`status ${item.status}`}>{item.status==='published'?'Нийтэлсэн':item.status==='processing'?'Боловсруулж байна':'Ноорог'}</span><span>{item.year}</span><button aria-label="Үйлдэл">•••</button></div>)}</div>
 {open&&<div className="modal-backdrop"><form className="admin-modal upload-modal" onSubmit={uploadMovie}><div className="modal-title"><div><p className="section-kicker">ШИНЭ КОНТЕНТ</p><h2>Кино upload хийх</h2></div><button type="button" onClick={close} aria-label="Хаах">×</button></div><div className="upload-form-grid"><label>Киноны нэр <span>*</span><input autoFocus value={title} onChange={event=>setTitle(event.target.value)} placeholder="Жишээ: Алсын бараа" disabled={uploadState==='uploading'}/></label><label>Тайлбар <span>*</span><textarea value={synopsis} onChange={event=>setSynopsis(event.target.value)} placeholder="Киноны товч агуулга..." disabled={uploadState==='uploading'}/></label></div><fieldset disabled={uploadState==='uploading'}><legend>Ангилал <span>*</span></legend><div className="category-picker">{categories.map(category=><button type="button" className={selectedCategories.includes(category)?'selected':''} onClick={()=>toggleCategory(category)} key={category}>{selectedCategories.includes(category)?'✓ ':'+ '}{category}</button>)}</div></fieldset>
 <div className={`video-dropzone ${video?'has-file':''}`} onClick={()=>uploadState!=='uploading'&&fileInput.current?.click()} onDragOver={event=>event.preventDefault()} onDrop={event=>{event.preventDefault();if(uploadState!=='uploading')setVideo(event.dataTransfer.files[0]??null)}}><input ref={fileInput} type="file" accept="video/mp4,video/quicktime,video/x-matroska,application/x-mpegURL,.mp4,.mov,.mkv,.m3u8" onChange={event=>setVideo(event.target.files?.[0]??null)}/><i>{video?'✓':'↑'}</i><div><b>{video?video.name:'Видео файлаа энд чирж оруулна уу'}</b><span>{video?`${(video.size/1024/1024).toFixed(1)} MB · Солих бол дарна уу`:'эсвэл дарж төхөөрөмжөөсөө сонгоно уу'}</span><small>MP4, MOV, MKV, M3U8 · Хэсэгчлэн upload хийнэ</small></div></div>
 {uploadState!=='idle'&&<div className={`upload-progress ${uploadState}`}><div><b>{uploadState==='uploading'?`Upload хийж байна — ${progress}%`:uploadState==='processing'?'Видео хадгалагдлаа, бүртгэл үүсгэж байна…':uploadState==='done'?'Амжилттай upload хийгдлээ':'Upload амжилтгүй'}</b><span>{video?.name}</span></div><div className="progress-track"><i style={{width:`${progress}%`}}/></div></div>}{error&&<p className="form-error">⚠ {error}</p>}<div className="modal-actions"><button type="button" onClick={close} disabled={uploadState==='uploading'}>Болих</button><button className="primary-button" disabled={uploadState==='uploading'||uploadState==='processing'||uploadState==='done'}>{uploadState==='uploading'?'Upload хийж байна…':'Upload хийгээд хадгалах'}</button></div></form></div>}</>}
