export type ContentKind = "movie" | "series";
export type AudioLabel = "Субтай" | "Хэлтэй";
export const audioLabels: AudioLabel[] = ["Субтай", "Хэлтэй"];
import type { SubtitleTrack } from "./storage/types";
export type ContentItem = {
  id: string;
  slug: string;
  title: string;
  synopsis: string;
  year: number;
  duration: string;
  age: string;
  rating: number;
  genre: string[];
  kind: ContentKind;
  status: "published" | "draft" | "processing";
  accent: string;
  episodes?: number;
  videoKey?: string;
  videoBytes?: number;
  subtitles?: SubtitleTrack[];
  posterUrl?: string;
  backdropUrl?: string;
  featured?: boolean;
  backdropPositionX?: number;
  backdropPositionY?: number;
  backdropZoom?: number;
  seriesTitle?: string;
  seriesId?: string;
  seasonId?: string;
  seasonNumber?: number;
  episodeNumber?: number;
  audioLabel?: AudioLabel;
};
export const content: ContentItem[] = [];
export const getContent = (slug: string) =>
  content.find((item) => item.slug === slug);
