import { env } from 'cloudflare:workers';
import { getChatGPTUser } from '@/app/chatgpt-auth';
export const dynamic = 'force-dynamic';
type Bindings = { MEDIA: R2Bucket; DB: D1Database };
const bindings = env as unknown as Bindings;
const allowedExtensions = new Set(['mp4','mov','mkv','m3u8']);
const unauthorized = () => Response.json({ error: 'Нэвтрэх шаардлагатай.' }, { status: 401 });
const safeExtension = (filename:string) => { const extension=filename.split('.').pop()?.toLowerCase()??''; return allowedExtensions.has(extension)?extension:null };
export async function POST(request:Request){
 const user=await getChatGPTUser();if(!user)return unauthorized();const body=await request.json() as Record<string,unknown>;
 if(body.action==='init'){const filename=String(body.filename??'');const extension=safeExtension(filename);if(!extension)return Response.json({error:'Дэмжигдээгүй видео формат.'},{status:400});const key=`movies/${new Date().toISOString().slice(0,10)}/${crypto.randomUUID()}.${extension}`;const upload=await bindings.MEDIA.createMultipartUpload(key,{httpMetadata:{contentType:String(body.contentType||'application/octet-stream')},customMetadata:{uploaderId:user.userId,originalName:filename}});return Response.json({key,uploadId:upload.uploadId})}
 if(body.action==='complete'){const key=String(body.key??'');const uploadId=String(body.uploadId??'');if(!key.startsWith('movies/')||!uploadId)return Response.json({error:'Upload мэдээлэл буруу.'},{status:400});const parts=Array.isArray(body.parts)?body.parts as R2UploadedPart[]:[];const movie=body.movie as {title?:string;synopsis?:string;categories?:string[];filename?:string;bytes?:number;contentType?:string}|undefined;if(!parts.length||!movie?.title||!movie.synopsis||!movie.categories?.length)return Response.json({error:'Киноны мэдээлэл дутуу.'},{status:400});await bindings.MEDIA.resumeMultipartUpload(key,uploadId).complete(parts);await bindings.DB.prepare(`CREATE TABLE IF NOT EXISTS movies (id TEXT PRIMARY KEY, slug TEXT NOT NULL UNIQUE, title TEXT NOT NULL, synopsis TEXT NOT NULL, categories TEXT NOT NULL, video_key TEXT NOT NULL, original_filename TEXT NOT NULL, content_type TEXT, bytes INTEGER NOT NULL DEFAULT 0, status TEXT NOT NULL DEFAULT 'processing', created_by TEXT NOT NULL, created_at TEXT NOT NULL)`).run();const id=crypto.randomUUID();const slug=`movie-${id.slice(0,8)}`;await bindings.DB.prepare(`INSERT INTO movies (id,slug,title,synopsis,categories,video_key,original_filename,content_type,bytes,status,created_by,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)`).bind(id,slug,movie.title,movie.synopsis,JSON.stringify(movie.categories),key,movie.filename??'',movie.contentType??'',Number(movie.bytes??0),'processing',user.userId,new Date().toISOString()).run();return Response.json({id,slug,status:'processing'})}
 return Response.json({error:'Тодорхойгүй үйлдэл.'},{status:400});
}
export async function PUT(request:Request){const user=await getChatGPTUser();if(!user)return unauthorized();const url=new URL(request.url);const key=url.searchParams.get('key')??'';const uploadId=url.searchParams.get('uploadId')??'';const partNumber=Number(url.searchParams.get('part'));if(!key.startsWith('movies/')||!uploadId||!Number.isInteger(partNumber)||partNumber<1||partNumber>10000)return Response.json({error:'Upload хэсгийн мэдээлэл буруу.'},{status:400});const bytes=await request.arrayBuffer();if(!bytes.byteLength)return Response.json({error:'Хоосон хэсэг.'},{status:400});const part=await bindings.MEDIA.resumeMultipartUpload(key,uploadId).uploadPart(partNumber,bytes);return Response.json({partNumber:part.partNumber,etag:part.etag})}
